### ISSUE TITLE
Add support for neosnippets

### ISSUE THREAD

**Issue by vigoux** [haorenW1025/completion-nvim#2]
(This issue follows the suggestions made [here](https://www.reddit.com/r/neovim/comments/fhcdzu/a_async_completion_framework_aims_to_support/fkb2ze4?utm_source=share&utm_medium=web2x))

Hello, thanks for the plugin, I'm really impatient to use it as my daily driver !

The thing is that for now it does not support [neosnippets](https://github.com/Shougo/neosnippet.vim), which would be great, is it possible to implement this, and how can I help on this ?

**Comment by haorenW1025** [comment]
I'm not familiar with neosnippets though, can you tell me how to get a list of all snippet in current file and how to expand the snippets?

**Comment by vigoux** [comment]
Getting snippet list (actually a dict) is done through `neosnippet#helpers#get_compeletion_snippets`.
Expanding is done through `neosnippet#expand` I think

**Comment by haorenW1025** [comment]
I can't get `neosnippet#expand` to work though..., so I'm using `execute "normal \<Plug>(neosnippet_expand)"` instead. It should be working now, please update and check.

**Comment by vigoux** [comment]
I'll check it out tomorrow.

**Comment by vigoux** [comment]
I just checked the snippet completion, and it works, a problem still remains with snippet expansion though, which don't seem to work.

**Comment by haorenW1025** [comment]
Yeah I also just found out it sometimes work but sometimes it doesn't. I make an update that used `nvim_feedkeys` as a workaround, please check if it works again, thanks

**Comment by vigoux** [comment]
I still have a bug, and found a way to reproduce :
* Start inserting
* Enter the start of a snippet
* Don't hit tab, just confirm completion
* The snippet name will be completed but without expanding it

**Comment by haorenW1025** [comment]
![Kapture 2020-03-13 at 17 30 45](https://user-images.githubusercontent.com/35623968/76608370-77ce0180-6550-11ea-8728-6bd9c58db2b6.gif)
Not sure about the reproduce step so I made a little gif to clarify that. Do you mean that in the first case in the video we should also expand the snippets?

**Comment by vigoux** [comment]
Hmmm, yeah, I changed my config a bit to use `noselect` in `completeopt`

Actually this behavior, forcing you to select an entry before completing seems better thant the one I had before.

I think that this closes the issue, thanks for the hard work !

Do I open another issue for multiple completion sources ?

**Comment by haorenW1025** [comment]
Oh okay, feel free to open again if there's any unexpected behavior:)
