### ISSUE TITLE
Unreliable Behavior for `g:completion_auto_change_source`

### ISSUE THREAD

**Issue by Furkanzmc** [haorenW1025/completion-nvim#98]
When `g:completion_auto_change_source` is enabled,  the automatic switch works for a few times and then it breaks. I have to exit the insert mode and then come back to make it work properly again.

Check out the gif for a demonstration.

![Screen Recording 2020-06-03 at 16 37 29](https://user-images.githubusercontent.com/932717/83687592-fc617680-a5b9-11ea-897e-bf9f8015f762.gif)

**My testing minimal init.vim**
```vim
packadd nvim-lsp
packadd completion-nvim


" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect

let g:completion_enable_auto_popup = 1
" Same result with
" let g:completion_enable_auto_popup = 0

let g:completion_auto_change_source = 1
let g:completion_matching_ignore_case = 1
let g:completion_timer_cycle = 200

function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <TAB>
            \ pumvisible() ? "\<C-n>" :
            \ <SID>check_back_space() ? "\<TAB>" :
            \ completion#trigger_completion()

inoremap <expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<S-TAB>"

let s:lsp_chain_config = [
            \   {'complete_items': ['lsp']},
            \   {'mode': '<c-p>'},
            \   {'mode': '<c-n>'},
            \   {'mode': 'file'},
            \ ]

let g:completion_chain_complete_list = {
            \ 'python' : s:lsp_chain_config,
            \ 'cpp' : s:lsp_chain_config,
            \ 'rust' : s:lsp_chain_config,
            \ 'default' : [
            \     {'mode': '<c-p>'},
            \     {'mode': '<c-n>'},
            \     {'mode': 'file'},
            \ ]
            \ }

lua require'nvim_lsp'.pyls.setup{on_attach=require'completion'.on_attach}
au Filetype python setl omnifunc=v:lua.vim.lsp.omnifunc
```

**How to reproduce**
1. Run NeoVim with `nvim -u minimumrc.vim ./playground.py --noplugins`
2. Write some code that has valid completion items from the LSP. Then delete it and write some random words that also exist in the buffer.
3. Without existing the insert mode, write some code that has valid completion items from the LSP again.
4. Completion breaks.

**Expected behavior**

The automatic switching of completion providers should not require us to exit insert mode and come back to it again to work.

**Comment by haorenW1025** [comment]
Sorry but I can't reproduce on my side, but I admit the chain_completion is kind of buggy. I'll try to improve that but it'll be better if you can give my another reproduce guide.
![Peek 2020-06-04 15-51](https://user-images.githubusercontent.com/35623968/83730445-ac4ae880-a67b-11ea-9c17-ab2258cc97df.gif)

**Comment by nhooyr** [comment]
I'll keep an eye out for this as well. I have noticed some general bugginess at the start but it seems to be fine now.

**Comment by nhooyr** [comment]
My config looks like this:

```vim
  set completeopt=menuone,noselect
  set pumheight=10

  let g:completion_trigger_keyword_length = 3
  let g:completion_matching_strategy_list = ['exact', 'substring', 'fuzzy']
  let g:completion_matching_ignore_case = 1
  let g:completion_auto_change_source = 1
  let g:completion_enable_snippet = 'Neosnippet'
  let g:completion_confirm_key = ""
  let g:completion_chain_complete_list = [
        \{'complete_items': ['lsp', 'snippet']},
        \{'mode': '<c-p>'},
        \{'mode': 'path'}
        \]
  imap <C-k> <cmd>lua require'source'.nextCompletion()<CR>
  inoremap <silent> <expr> <C-space> completion#trigger_completion()
```

**Comment by Shatur95** [comment]
Same here. Can reproduce in 100% times with clang. I think this can be related with language server.

Try the following:

1. Install `clangd`
2. Download simple CMake project, for example [akd](https://github.com/Shatur95/akd).
3. Then `mkdir build && cd build && cmake -D CMAKE_EXPORT_COMPILE_COMMANDS ..`
4. Open any Cpp file, and try to complete.

Here is the video:

[![asciicast](https://asciinema.org/a/2GCbkyGPcE7942vlcrTZPD0go.svg)](https://asciinema.org/a/2GCbkyGPcE7942vlcrTZPD0go)

In the end of the video I iterated over sources to show that buffers source have completion items.

**Comment by Furkanzmc** [comment]
I was able to work around this by adding a new `firstCompletion` function and adding this `autocmd`.

```vim
autocmd InsertLeave,CompleteDone * :lua require'source'.firstCompletion()
```

With this, it works as expected if I leave insert mode or do `<c-e>`

**Comment by haorenW1025** [comment]
I can reproduce with @Shatur95 method, thanks! Will try to look into this.

@Furkanzmc I think in my implementation I'll reset the completion on every new word or upon any deletion.

**Comment by haorenW1025** [comment]
I've pushed some fix. @Shatur95 @Furkanzmc Can you check if you can reproduce now?

**Comment by Shatur95** [comment]
I using completion-buffers instead of ins-complete and it did not helped :(

**Comment by Furkanzmc** [comment]
@haorenW1025 Using the same configuration. Now I only see completion items from the LSP and not the other sources.

![Screen Recording 2020-06-06 at 17 18 46](https://user-images.githubusercontent.com/932717/83954764-0da8be00-a81a-11ea-837a-84026bc20905.gif)

**Comment by Shatur95** [comment]
> I using completion-buffers instead of ins-complete and it did not helped :(

I meant that the issue exists with external sources too. But I see that you applied fixes for ins-completion. Maybe the issue is not related to only ins-compilation?..

**Comment by haorenW1025** [comment]
Okay I think I should revert back the changes cause it seems not helping at all... @Furkanzmc I'll look into the manual trigger behavior.
@Shatur95 I would start testing with `completion-buffers`. Thanks for the input:)

**Comment by haorenW1025** [comment]
@Furkanzmc I can't reproduce on the latest master, I pushed some code today, can you update and check?
![Peek 2020-06-07 20-49](https://user-images.githubusercontent.com/35623968/83969084-6488c300-a900-11ea-9da2-1d672f1f4650.gif)

**Comment by Furkanzmc** [comment]
@haorenW1025 I have bad news. The latest updates breaks everything for me. Neither the auto popup nor the manual trigger works. I have to manually call `<C-x><C-o>` to get the LSP completion. I do exact same things that you do in your gif, and nothing pops up.

 I worked my way back from the latest commit to see which one starts working for me, and the latest commit that works is d080b93. Is there any additional information I can provide you?

**Comment by haorenW1025** [comment]
Yeah I've got a similar report in #106, but everything seems fine on my side so it's hard for me to debug...I'll try revert some changes and see how it goes.

**Comment by haorenW1025** [comment]
I guess bfcb99a7f143e1835fa47c93afce5a20ea7d2845 is breaking the whole completion. I've reverted the changes and seems to fix the issue. @Furkanzmc Please update and check if it works.

**Comment by Furkanzmc** [comment]
@haorenW1025 Now auto popup works. But the chain completion does not. The situation is the same as in [this comment](https://github.com/haorenW1025/completion-nvim/issues/98#issuecomment-640119745)

**Comment by haorenW1025** [comment]
The latest commit should fix it with auto-popup is 1. As for the manual trigger part I have to investigate more time to find the cause.. Please update and check.

**Comment by Furkanzmc** [comment]
@haorenW1025 I can confirm that the latest commit 565db83d2902ef4a9c3be726ec340ffd7fe7edb6 fixes the problem for auto popup.

It seems that manual completion is a separate issue. It still doesn't work. I can update this issue, or I can create a new issue just for that one. If you prefer that I create a new one, you can close this issue and I'll create the new one. Otherwise, I'll keep updating this issue.

Thanks for the fix.

**Comment by haorenW1025** [comment]
I made an update that every manual completion will reset chain completion. This should fix the issue with manually triggered. Also it can be used to reset completion if something breaks in auto-popup is on.

**Comment by Furkanzmc** [comment]
This works great. It solves my problem. Thanks for the fix @haorenW1025. I'm closing the issue.

**Comment by Shatur95** [comment]
@haorenW1025, completion-buffers still have the same problem. Should I open a new issue here?

**Comment by haorenW1025** [comment]
@Shatur95 Please open a new issue, thanks:)
